#@data/values
---
#! control optional deployment of a database for CF
cf_db:
  admin_password: ""

#! reserved static ip for istio LoadBalancer
istio_static_ip: ""

system_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.system.cf.example.com)
  crt: ""
  #! Base64-encoded private key for the system certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the system certifcate
  ca: ""

workloads_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.apps.cf.example.com)
  crt: ""
  #! Base64-encoded private key for the workloads certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the workloads certifcate
  ca: ""

internal_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.cf-system.svc.cluster.local)
  crt: ""
  #! Base64-encoded private key for the internal certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the internal certifcate
  ca: ""

log_cache_ca:
  crt: "" #! Base64-encoded ca for the log cache
  key: "" #! Base64-encoded private key for the cert above

log_cache:
  crt: "" #! Base64-encoded cert for the log cache requires CN of log-cache
  key: "" #! Base64-encoded private key for the cert above

log_cache_metrics:
  crt: "" #! Base64-encoded cert for the log cache metrics requires CN of log-cache-metrics
  key: "" #! Base64-encoded private key for the cert above

log_cache_gateway:
  crt: "" #! Base64-encoded cert for the log cache gateway requires CN of log-cache-gateway
  key: "" #! Base64-encoded private key for the cert above

log_cache_syslog:
  crt: "" #! Base64-encoded cert for the log cache syslog server requires CN of log-cache-syslog
  key: "" #! Base64-encoded private key for the cert above

app_registry:
  hostname: ""
  repository_prefix: ""
  username: ""
  password: ""
