#@data/values
---
#! control optional deployment of a database for CF
cf_db:
  admin_password: ""

#! reserved static ip for istio LoadBalancer
istio_static_ip: ""

system_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.system.cf.example.com)
  crt: ""
  #! Base64-encoded private key for the system certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the system certifcate
  ca: ""

workloads_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.apps.cf.example.com)
  crt: ""
  #! Base64-encoded private key for the workloads certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the workloads certifcate
  ca: ""

internal_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.cf-system.svc.cluster.local)
  crt: ""
  #! Base64-encoded private key for the internal certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the internal certifcate
  ca: ""

app_registry:
  hostname: ""
  repository_prefix: ""
  username: ""
  password: ""
