#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ def metrics_values():
system_domain: #@ data.values.system_domain
system_namespace: #@ data.values.system_namespace
#@ end

#@ metrics = library.get("github.com/cloudfoundry/metric-proxy")
--- #@ template.replace(metrics.with_data_values(metrics_values()).eval())

