#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("must_exist.star", "must_exist")

#@ def add_cf_blobstore_namespace():
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: cf-blobstore
#@ end

---
apiVersion: v1
kind: Namespace
metadata:
  name: cf-blobstore

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "cf-blobstore-minio"}})
---
data:
  accesskey: #@ base64.encode(must_exist(data.values, "cf_blobstore.access_key"))
  secretkey: #@ base64.encode(must_exist(data.values, "cf_blobstore.secret_key"))

--- #@ template.replace(overlay.apply(library.get("minio").eval(), add_cf_blobstore_namespace()))

---
#! explanation: the blobstore's sidecar needs to accept plain text connections from kpack build init containers.
#! see https://github.com/cloudfoundry/capi-k8s-release/issues/12
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "cf-blobstore-allow-plaintext"
  namespace: "cf-blobstore"
spec:
  targets:
    - name: cf-blobstore-minio
  peers:
    - mtls:
        mode: PERMISSIVE
