#@data/values
---
uaa:
  #! client secret for uaa admin client in plain text
  admin_client_secret: ""

  database:
    #! or mysql2, as needed
    adapter: postgresql
    host: ""
    port: 5432
    user: uaa
    #! DB user password in plain text
    password: ""
    name: uaa
    #! Plain text ca certificate for tls
    ca_cert: ""

  jwt_policy:
    key_id: "default_jwt_policy_key"
    #! Plain text private key
    signing_key: ""

  encryption_key:
    label: "default_encryption_key"
    #! Plain text passphrase
    passphrase: ""

  login:
    service_provider:
      #! Plain text private key
      key: ""
      #! Plain text password
      key_password: ""
      #! Plain text certificate
      certificate: ""

  login_secret_name: "uaa-login-secret"

system_namespace: cf-system

#! control optional deployment of a database for CF
cf_db:
  enabled: true
