[[buildpacks]]
image = "gcr.io/paketo-community/python:0.0.2"

[[order]]
    [[order.group]]
    id = "paketo-community/python"
    version = "0.0.2"

[stack]
id = "org.cloudfoundry.stacks.cflinuxfs3"
build-image = "gcr.io/paketo-buildpacks/build:full-cnb-cf"
run-image = "gcr.io/paketo-buildpacks/run:full-cnb-cf"
